# Gesture Phase Segmentation

# 1. Loading the Dataset

In [1]:
%matplotlib inline
import pandas as pd

import numpy as np

from sklearn.model_selection import train_test_split
from sklearn import model_selection, metrics
from sklearn import preprocessing
from sklearn.utils import shuffle
from sklearn.preprocessing import StandardScaler

import matplotlib
import matplotlib.pyplot as plt

### 1.1 Reading the '.csv' Files

In [5]:
# read .csv from provided dataset
csv_filename01="a1_raw.csv"
csv_filename02="a1_va3.csv"
csv_filename03="a2_raw.csv"
csv_filename04="a2_va3.csv"
csv_filename05="a3_raw.csv"
csv_filename06="a3_va3.csv"

csv_filename07="b1_raw.csv"
csv_filename08="b1_va3.csv"
csv_filename09="b3_raw.csv"
csv_filename10="b3_va3.csv"

csv_filename11="c1_raw.csv"
csv_filename12="c1_va3.csv"
csv_filename13="c3_raw.csv"
csv_filename14="c3_va3.csv"

# df=pd.read_csv(csv_filename,index_col=0)
df1=pd.read_csv("a1_raw.csv" , skiprows=[1,2,3,4])
df2=pd.read_csv("a1_va3.csv")
df3=pd.read_csv("a2_raw.csv" , skiprows=[1,2,3,4])
df4=pd.read_csv("a2_va3.csv")
df5=pd.read_csv("a3_raw.csv" , skiprows=[1,2,3,4])
df6=pd.read_csv("a3_va3.csv")
df7=pd.read_csv("b1_raw.csv" , skiprows=[1,2,3,4])
df8=pd.read_csv("b1_va3.csv")
df9=pd.read_csv("b3_raw.csv" , skiprows=[1,2,3,4])
df10=pd.read_csv(csv_filename10)
df11=pd.read_csv(csv_filename11 , skiprows=[1,2,3,4])
df12=pd.read_csv(csv_filename12)
df13=pd.read_csv(csv_filename13 , skiprows=[1,2,3,4])
df14=pd.read_csv(csv_filename14)

### 1.2 Removing the 'timestamp' & 'phase' labels

In [6]:
df1.drop('timestamp',axis=1,inplace=True)
df1.drop('phase',axis=1,inplace=True)
df3.drop('timestamp',axis=1,inplace=True)
df3.drop('phase',axis=1,inplace=True)
df5.drop('timestamp',axis=1,inplace=True)
df5.drop('phase',axis=1,inplace=True)
df7.drop('timestamp',axis=1,inplace=True)
df7.drop('phase',axis=1,inplace=True)
df9.drop('timestamp',axis=1,inplace=True)
df9.drop('phase',axis=1,inplace=True)
df11.drop('timestamp',axis=1,inplace=True)
df11.drop('phase',axis=1,inplace=True)
df13.drop('timestamp',axis=1,inplace=True)
df13.drop('phase',axis=1,inplace=True)

### 1.3 Visualising the Table 1

In [8]:
df1.head()

lhx       lhy       lhz       rhx       rhy       rhz        hx  \
0  5.003160  4.278530  1.542866  4.985812  4.182155  1.520330  5.037557   
1  5.064488  4.290401  1.542146  4.955739  4.163175  1.511876  5.037724   
2  5.067825  4.290883  1.542058  4.928284  4.157637  1.511306  5.038332   
3  5.070332  4.290677  1.541985  4.916637  4.151067  1.510510  5.038742   
4  5.071611  4.290927  1.542046  4.906132  4.143034  1.509449  5.042224   

         hy        hz        sx        sy        sz       lwx       lwy  \
0  1.619226  1.778925  5.052367  4.225485  1.775536  4.983912  4.296833   
1  1.618397  1.779722  5.045395  4.223284  1.777401  5.000410  4.301358   
2  1.618043  1.780080  5.045374  4.223690  1.777571  5.001656  4.299812   
3  1.618044  1.780114  5.045767  4.224827  1.777669  5.002672  4.298810   
4  1.618561  1.780209  5.047422  4.223671  1.778054  5.012298  4.298582   

        lwz       rwx       rwy       rwz  
0  1.569889  5.193762  4.335417  1.560144  
1  1.566544  5.164159  4.313107  1.552097  
2  1.566537  5.136817  4.307087  1.551576  
3  1.566489  5.125220  4.300282  1.550805  
4  1.565061  5.114789  4.292008  1.549765

In [9]:
df1.shape

(1743, 18)

### 1.4 Visualising the Table 2

In [10]:
df2.head()

1         2         3         4         5         6         7  \
0 -0.005009 -0.000964  0.000573  0.008623  0.005667  0.001302 -0.000631   
1  0.004905  0.001209 -0.000649  0.004737  0.003166  0.000819 -0.000572   
2 -0.002393 -0.000216  0.000136  0.003028  0.001212  0.000336 -0.000449   
3 -0.001394 -0.000242  0.000056  0.001182  0.000575  0.000225 -0.000479   
4 -0.000156 -0.000004  0.000023  0.001585  0.000630  0.000094 -0.000303   

          8         9        10  ...            24        25        26  \
0  0.000130 -0.000048  0.007762  ...  1.880800e-04  0.005133  0.010400   
1 -0.000015  0.000023  0.002706  ... -7.500000e-07  0.005093  0.005756   
2  0.000017  0.000047  0.002868  ... -3.920000e-05  0.002406  0.003279   
3 -0.000050  0.000104  0.001171  ... -3.184000e-05  0.001416  0.001334   
4  0.000097  0.000065  0.001579  ... -2.015000e-05  0.000158  0.001709   

         27        28        29        30        31        32  Phase  
0  0.000646  0.007871  0.004631  0.000963  0.000092  0.000438      D  
1  0.000573  0.003459  0.000730  0.000332  0.000012  0.000433      D  
2  0.000452  0.003261  0.002412  0.000852  0.000042  0.000202      D  
3  0.000493  0.001358  0.000313  0.000611  0.000029  0.000596      D  
4  0.000325  0.001713  0.000203  0.000069  0.000038  0.000069      D  

[5 rows x 33 columns]

In [11]:
df2.shape

(1743, 33)

In [12]:
df2.Phase.unique()

array(['D', 'P', 'S', 'H', 'R'], dtype=object)

Visualising the Column Labels in the two tables.

In [13]:
df1.columns

Index(['lhx', 'lhy', 'lhz', 'rhx', 'rhy', 'rhz', 'hx', 'hy', 'hz', 'sx', 'sy',
       'sz', 'lwx', 'lwy', 'lwz', 'rwx', 'rwy', 'rwz'],
      dtype='object')

In [14]:
df2.columns

Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13',
       '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25',
       '26', '27', '28', '29', '30', '31', '32', 'Phase'],
      dtype='object')

### 1.5 Renaming 'Phase' Column for convinience

In [15]:
df2.rename(columns={'Phase': 'phase'}, inplace=True)
df4.rename(columns={'Phase': 'phase'}, inplace=True)
df6.rename(columns={'Phase': 'phase'}, inplace=True)
df8.rename(columns={'Phase': 'phase'}, inplace=True)
df10.rename(columns={'Phase': 'phase'}, inplace=True)
df12.rename(columns={'Phase': 'phase'}, inplace=True)
df14.rename(columns={'Phase': 'phase'}, inplace=True)

___

### 1.6 Concatenating the Dataframes 

In [16]:
p1 = pd.concat([df1,df2],axis=1)
p2 = pd.concat([df3,df4],axis=1)
p3 = pd.concat([df5,df6],axis=1)
p4 = pd.concat([df7,df8],axis=1)
p5 = pd.concat([df9,df10],axis=1)
p6 = pd.concat([df11,df12],axis=1)
p7 = pd.concat([df13,df14],axis=1)

In [17]:
df= pd.concat([p1,p2,p3,p4,p5,p6,p7])

### 1.7 Encoding Phase Labels and Estimating number of instances of Differrent Labels

In [18]:
df.phase.unique()

array(['D', 'P', 'S', 'H', 'R'], dtype=object)

In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['phase'] = le.fit_transform(df['phase'])

In [20]:
df.groupby('phase').count()

lhx   lhy   lhz   rhx   rhy   rhz    hx    hy    hz    sx  ...    23  \
phase                                                              ...         
0      2741  2741  2741  2741  2741  2741  2741  2741  2741  2741  ...  2741   
1       998   998   998   998   998   998   998   998   998   998  ...   998   
2      2097  2097  2097  2097  2097  2097  2097  2097  2097  2097  ...  2097   
3      1087  1087  1087  1087  1087  1087  1087  1087  1087  1087  ...  1087   
4      2950  2950  2950  2950  2950  2950  2950  2950  2950  2950  ...  2950   

         24    25    26    27    28    29    30    31    32  
phase                                                        
0      2741  2741  2741  2741  2741  2741  2741  2741  2741  
1       998   998   998   998   998   998   998   998   998  
2      2097  2097  2097  2097  2097  2097  2097  2097  2097  
3      1087  1087  1087  1087  1087  1087  1087  1087  1087  
4      2950  2950  2950  2950  2950  2950  2950  2950  2950  

[5 rows x 50 columns]

In [21]:
df.phase.unique()

array([0, 2, 4, 1, 3], dtype=int64)

___

### 1.8 Randomising the Data before Splitting

#### Before:

In [22]:
df.head()

lhx       lhy       lhz       rhx       rhy       rhz        hx  \
0  5.003160  4.278530  1.542866  4.985812  4.182155  1.520330  5.037557   
1  5.064488  4.290401  1.542146  4.955739  4.163175  1.511876  5.037724   
2  5.067825  4.290883  1.542058  4.928284  4.157637  1.511306  5.038332   
3  5.070332  4.290677  1.541985  4.916637  4.151067  1.510510  5.038742   
4  5.071611  4.290927  1.542046  4.906132  4.143034  1.509449  5.042224   

         hy        hz        sx  ...            24        25        26  \
0  1.619226  1.778925  5.052367  ...  1.880800e-04  0.005133  0.010400   
1  1.618397  1.779722  5.045395  ... -7.500000e-07  0.005093  0.005756   
2  1.618043  1.780080  5.045374  ... -3.920000e-05  0.002406  0.003279   
3  1.618044  1.780114  5.045767  ... -3.184000e-05  0.001416  0.001334   
4  1.618561  1.780209  5.047422  ... -2.015000e-05  0.000158  0.001709   

         27        28        29        30        31        32  phase  
0  0.000646  0.007871  0.004631  0.000963  0.000092  0.000438      0  
1  0.000573  0.003459  0.000730  0.000332  0.000012  0.000433      0  
2  0.000452  0.003261  0.002412  0.000852  0.000042  0.000202      0  
3  0.000493  0.001358  0.000313  0.000611  0.000029  0.000596      0  
4  0.000325  0.001713  0.000203  0.000069  0.000038  0.000069      0  

[5 rows x 51 columns]

In [23]:
df = df.sample(frac=1)

#### After:

In [24]:
df.head()

lhx       lhy       lhz       rhx       rhy       rhz        hx  \
845   2.277555  3.970724  2.221838  3.381155  4.140748  2.336679  2.437081   
1575  5.123733  4.318799  1.464153  4.599277  4.306388  1.478625  5.195059   
90    1.764019  3.699169  1.972412  2.478628  3.989543  1.930437  2.601864   
69    4.633566  4.880719  2.389491  4.782607  5.045462  2.559065  4.713011   
48    4.543792  4.999423  2.461591  4.782104  4.910508  2.441726  4.661849   

            hy        hz        sx  ...        24        25        26  \
845   0.824407  2.403795  2.478526  ... -0.000030  0.003264  0.000909   
1575  1.649535  1.781793  5.035421  ... -0.000047  0.000209  0.001220   
90    1.285705  2.239621  2.540034  ...  0.000075  0.006555  0.005797   
69    4.707355  2.699297  4.669218  ...  0.004366  0.013334  0.018616   
48    4.699667  2.731979  4.643966  ...  0.000599  0.042015  0.018760   

            27        28        29        30        31        32  phase  
845   0.002579  0.000613  0.000417  0.000052  0.000314  0.000087      0  
1575  0.000164  0.000974  0.000312  0.000114  0.000234  0.000073      0  
90    0.005964  0.006172  0.000310  0.000314  0.000276  0.000731      2  
69    0.011388  0.008123  0.010288  0.002335  0.008363  0.004494      4  
48    0.037367  0.015194  0.004883  0.003908  0.005057  0.001751      2  

[5 rows x 51 columns]

### 1.9 Extracting the Feautre & Label Vector + Splitting into Test & Train (60:40)

In [25]:
cols = list(df.columns)
features = cols
features.remove('phase')

In [26]:
len(features)

50

In [27]:
X = df[features]
y = df['phase']
X.shape

(9873, 50)

In [28]:
# split dataset to 60% training and 40% testing
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.4, random_state=0)

### 1.10 Normalize the Dataset for Easier Parameter Selection

In [29]:
X_train = StandardScaler().fit_transform(X_train)
X_test = StandardScaler().fit_transform(X_test)

In [30]:
print(X_train.shape, y_train.shape)

(5923, 50) (5923,)


___

# PCA - Principal Component Analysis

In [68]:
len(features)

50

In [66]:
# First we reduce the data to two dimensions using PCA to capture variation
pca = PCA(n_components=2)
reduced_data = pca.fit_transform(X)
#print(reduced_data[:10])  # print upto 10 elements

In [67]:
reduced_data.shape

(9873, 2)

____

# 2. Classification Modals

In [69]:
import os
from sklearn.tree import DecisionTreeClassifier, export_graphviz
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn import model_selection, metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.decomposition import PCA

from time import time
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score , classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.metrics import precision_score, recall_score, accuracy_score, classification_report

In [71]:
# First we reduce the data to two dimensions using PCA to capture variation
pca = PCA(n_components=10)
X = pca.fit_transform(X)
print(reduced_data[:10])  # print upto 10 elements

[[ 4.03558998 -0.58589872]
 [-1.95742879  0.57341377]
 [ 4.58515987 -0.71855315]
 [-2.03314468 -2.75786296]
 [-1.91854195 -2.7073702 ]
 [-2.01444889 -2.94259291]
 [-2.12392725 -2.57248311]
 [ 0.32256981  2.29440662]
 [-2.45099333  1.30024755]
 [ 3.68361949 -2.49138788]]


In [72]:
# split dataset to 60% training and 40% testing
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.4, random_state=0)

In [73]:
print (X_train.shape, y_train.shape,X_test.shape, y_test.shape)

(5923, 10) (5923,) (3950, 10) (3950,)


### 2.1 Feature Scaling

In [74]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import scale
from sklearn.preprocessing import StandardScaler

#1. MinMax Scaling
min_max=MinMaxScaler()
X_train_minmax=min_max.fit_transform(X_train)
X_test_minmax =min_max.fit_transform(X_test)

#2. Scale
X_train_scale =scale(X_train)
X_test_scale  =scale(X_test)

#3. Standard Scaler
X_train_Stdscaler = StandardScaler().fit_transform(X_train)
X_test_Stdscaler = StandardScaler().fit_transform(X_test)

___

### 2.2 Decision Tree accuracy and time elapsed caculation

In [75]:
dt = DecisionTreeClassifier(min_samples_split=20,random_state=99)
# dt = DecisionTreeClassifier(min_samples_split=20,max_depth=5,random_state=99)

In [76]:
tt0=time()

print ("cross result========")
scores = model_selection.cross_val_score(dt, X,y, cv=5)
print (scores)
print (scores.mean())
tt1=time()
print ("time elapsed: ", tt1-tt0)
print ("\n")

cross result========
[0.77946383 0.76720648 0.76038501 0.7511404  0.78053725]
0.7677465930284204
time elapsed:  0.5085868835449219




#### 2.2.1 Implementation 1

In [38]:
t0=time()
print ("DecisionTree: Case-1: Normal Unprocessed Data")

clf_dt1= dt.fit(X_train,y_train)

print ("Acurracy: ", clf_dt1.score(X_test,y_test))
t1=time()
print ("time elapsed: ", t1-t0)

DecisionTree: Case-1: Normal Unprocessed Data
Acurracy:  0.7346835443037975
time elapsed:  0.07476687431335449


#### 2.2.2 Implementation 2

In [39]:
t0=time()
print ("DecisionTree: Case-2: MinMax Feature Scaling")

clf_dt2= dt.fit(X_train_minmax,y_train)

print ("Acurracy: ", clf_dt2.score(X_test_minmax,y_test))
t1=time()
print ("time elapsed: ", t1-t0)

DecisionTree: Case-2: MinMax Feature Scaling
Acurracy:  0.609873417721519
time elapsed:  0.0747992992401123


#### 2.2.3 Implementation 3

In [40]:
t0=time()
print ("DecisionTree: Case-3: Scale")

clf_dt3= dt.fit(X_train_scale,y_train)

print ("Acurracy: ", clf_dt3.score(X_test_scale,y_test))
t1=time()
print ("time elapsed: ", t1-t0)

DecisionTree: Case-3: Scale
Acurracy:  0.6987341772151898
time elapsed:  0.07480573654174805


#### 2.2.4 Implementation 4

In [41]:
t0=time()
print ("DecisionTree: Case-4: Standard Scaler")

clf_dt4= dt.fit(X_train_Stdscaler,y_train)

print ("Acurracy: ", clf_dt4.score(X_test_Stdscaler,y_test))
t1=time()
print ("time elapsed: ", t1-t0)

DecisionTree: Case-4: Standard Scaler
Acurracy:  0.6987341772151898
time elapsed:  0.0788259506225586


___

### 2.3 Random Forest accuracy and time elapsed caculation

In [77]:
rf = RandomForestClassifier(n_estimators=100,n_jobs=-1)

In [78]:
tt2=time()
print ("cross result========")
scores = model_selection.cross_val_score(rf, X,y, cv=5)
print (scores)
print (scores.mean())
tt3=time()
print ("time elapsed: ", tt3-tt2)
print ("\n")

cross result========
[0.89074355 0.88866397 0.90020263 0.89406994 0.89863153]
0.8944623245068
time elapsed:  5.648023366928101




#### 2.3.1 Implementation 1

In [44]:
t2=time()
print ("RandomForest: Case-1 : Normal")
clf_rf1 = rf.fit(X_train,y_train)
print ("Acurracy: ", clf_rf1.score(X_test,y_test))
t3=time()

print ("time elapsed: ", t3-t2)

RandomForest: Case-1 : Normal
Acurracy:  0.8729113924050633
time elapsed:  0.729156494140625


#### 2.3.2 Implementation 2

In [45]:
t2=time()
print ("RandomForest: Case-2 : MinMax Feature Scaling")
clf_rf2 = rf.fit(X_train_minmax,y_train)
print ("Acurracy: ", clf_rf2.score(X_test_minmax,y_test))
t3=time()
print ("time elapsed: ", t3-t2)

RandomForest: Case-2 : MinMax Feature Scaling
Acurracy:  0.8058227848101266
time elapsed:  0.6133718490600586


#### 2.3.3 Implementation 3

In [46]:
t2=time()
print ("RandomForest: Case-3 : Scale")
clf_rf3 = rf.fit(X_train_scale,y_train)
print ("Acurracy: ", clf_rf3.score(X_test_scale,y_test))
t3=time()
print ("time elapsed: ", t3-t2)

RandomForest: Case-3 : Scale
Acurracy:  0.8559493670886076
time elapsed:  0.5977821350097656


#### 2.3.4 Implementation 4

In [47]:
t2=time()
print ("RandomForest: Case-2 : MinMax Feature Scaling")
clf_rf4 = rf.fit(X_train_Stdscaler,y_train)
print ("Acurracy: ", clf_rf4.score(X_test_Stdscaler,y_test))
t3=time()
print ("time elapsed: ", t3-t2)

RandomForest: Case-2 : MinMax Feature Scaling
Acurracy:  0.8562025316455696
time elapsed:  0.5932793617248535


___

### 2.4 Naive Bayes accuracy and time elapsed caculation


In [79]:
nb = BernoulliNB()

In [80]:
tt4=time()
print ("cross result========")
scores = model_selection.cross_val_score(nb, X,y, cv=5)
print (scores)
print (scores.mean())
tt5=time()
print ("time elapsed: ", tt5-tt4)
print ("\n")

cross result========
[0.52503794 0.54149798 0.5177305  0.53117081 0.52052712]
0.5271928660751497
time elapsed:  0.03892874717712402




In [81]:
t4=time()
print ("NaiveBayes")
clf_nb=nb.fit(X_train,y_train)
print ("Acurracy: ", clf_nb.score(X_test,y_test))
t5=time()
print ("time elapsed: ", t5-t4)

NaiveBayes
Acurracy:  0.5278481012658228
time elapsed:  0.0059833526611328125


___

### 2.5 KNN accuracy and time elapsed caculation

In [82]:
t6=time()
print ("KNN")
# knn = KNeighborsClassifier(n_neighbors=3)
knn = KNeighborsClassifier()
clf_knn=knn.fit(X_train, y_train)
print ("Acurracy: ", clf_knn.score(X_test,y_test) )
t7=time()
print ("time elapsed: ", t7-t6)

KNN
Acurracy:  0.8111392405063291
time elapsed:  0.1447436809539795


In [83]:
tt6=time()
print ("cross result========")
scores = model_selection.cross_val_score(clf_knn, X,y, cv=5)
print (scores)
print (scores.mean())
tt7=time()
print ("time elapsed: ", tt7-tt6)
print ("\n")

cross result========
[0.83459788 0.83198381 0.84549139 0.85250887 0.85504308]
0.8439250041249544
time elapsed:  0.36234116554260254




___

### 2.6 SVM Accuracy and Time Elapsed Calculation

#### 2.6.1 SVM with a Linear Kernel 

In [84]:
t7=time()
print ("SVM")

svc = SVC()
clf_svc=svc.fit(X_train_minmax, y_train)
print ("Acurracy: ", clf_svc.score(X_test_minmax,y_test) )
t8=time()
print ("time elapsed: ", t8-t7)

SVM


C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Acurracy:  0.5273417721518987
time elapsed:  1.7020576000213623


In [85]:
tt7=time()
print ("cross result========")
scores = model_selection.cross_val_score(clf_svc, X,y, cv=5)
print (scores)
print (scores.mean())
tt8=time()
print ("time elapsed: ", tt8-tt7)
print ("\n")

cross result========


C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: 

[0.65351543 0.65637652 0.64690983 0.65027876 0.66092245]
0.6536005979632967
time elapsed:  9.337402582168579




#### 2.6.2 SVM with Multiple Kernels 

In [86]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn import model_selection

svc = SVC()

parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10, 100]}

grid = model_selection.GridSearchCV(svc, parameters, n_jobs=-1, verbose=1, scoring='accuracy')


grid.fit(X_train, y_train)

print ('Best score: %0.3f' % grid.best_score_)

print ('Best parameters set:')
best_parameters = grid.best_estimator_.get_params()

for param_name in sorted(parameters.keys()):
    print ('\t%s: %r' % (param_name, best_parameters[param_name]))
    
predictions = grid.predict(X_test)
print (classification_report(y_test, predictions))

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 3 folds for each of 6 candidates, totalling 18 fits


[Parallel(n_jobs=-1)]: Done  18 out of  18 | elapsed:  3.0min finished
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Best score: 0.751
Best parameters set:
	C: 100
	kernel: 'rbf'
              precision    recall  f1-score   support

           0       0.80      0.98      0.88      1070
           1       0.68      0.66      0.67       392
           2       0.65      0.61      0.63       823
           3       0.77      0.46      0.58       437
           4       0.84      0.83      0.83      1228

    accuracy                           0.77      3950
   macro avg       0.75      0.71      0.72      3950
weighted avg       0.76      0.77      0.76      3950



In [87]:
pipeline = Pipeline([
    ('clf', SVC(kernel='rbf', gamma=0.01, C=100))
])

parameters = {
    'clf__gamma': (0.01, 0.03, 0.1, 0.3, 1),
    'clf__C': (0.1, 0.3, 1, 3, 10, 30),
}

grid_search = GridSearchCV(pipeline, parameters, n_jobs=-1, verbose=1, scoring='accuracy')

grid_search.fit(X_train, y_train)

print ('Best score: %0.3f' % grid_search.best_score_)

print ('Best parameters set:')
best_parameters = grid_search.best_estimator_.get_params()

for param_name in sorted(parameters.keys()):
    print ('\t%s: %r' % (param_name, best_parameters[param_name]))
    
predictions = grid_search.predict(X_test)
print (classification_report(y_test, predictions))

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 3 folds for each of 30 candidates, totalling 90 fits


[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    5.0s
[Parallel(n_jobs=-1)]: Done  90 out of  90 | elapsed:   11.3s finished


Best score: 0.824
Best parameters set:
	clf__C: 30
	clf__gamma: 1
              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1070
           1       0.77      0.84      0.80       392
           2       0.79      0.78      0.78       823
           3       0.86      0.68      0.76       437
           4       0.93      0.88      0.90      1228

    accuracy                           0.86      3950
   macro avg       0.84      0.83      0.83      3950
weighted avg       0.86      0.86      0.86      3950



___

### 2.7 Leveraging weak learners via adaptive boosting

In [89]:
from sklearn.ensemble import AdaBoostClassifier

tree = DecisionTreeClassifier(criterion='entropy', 
                              max_depth=1)

ada = AdaBoostClassifier(base_estimator=tree,
                         n_estimators=500, 
                         learning_rate=0.1,
                         random_state=0)

tree = tree.fit(X_train, y_train)
y_train_pred = tree.predict(X_train)
y_test_pred = tree.predict(X_test)

tree_train = accuracy_score(y_train, y_train_pred)
tree_test = accuracy_score(y_test, y_test_pred)
print('Decision tree train/test accuracies %.3f/%.3f'
      % (tree_train, tree_test))

ada = ada.fit(X_train, y_train)
y_train_pred = ada.predict(X_train)
y_test_pred = ada.predict(X_test)

ada_train = accuracy_score(y_train, y_train_pred) 
ada_test = accuracy_score(y_test, y_test_pred) 
print('AdaBoost train/test accuracies %.3f/%.3f'
      % (ada_train, ada_test))

Decision tree train/test accuracies 0.414/0.410
AdaBoost train/test accuracies 0.574/0.561


___